project:
  type: website
  output-dir: docs

website:
  title: "CodeRs: Scaling up with R and Katana"
  description: ""
  navbar:
    background: "#e6f4f1"
    foreground: dark
    left:
      - text: Getting Started
        menu:
          - href: getting_started/login.qmd
            text: "Logging in"
          - href: getting_started/commands.qmd
            text: "Shell commands"
          - href: getting_started/transfer.qmd
            text: "Transferring files"
      - text: Running R
        menu:
          - href: running_r/interactive.qmd
            text: "Interactive R session"
          - href: running_r/job.qmd
            text: "Running a job"
      - text: Advanced
        menu:
          - href: advanced/environment.qmd
            text: "Passing values"
          - href: advanced/loops.qmd
            text: "Loops"
    right:
      - icon: github
        href: https://github.com/kristenbhunter/codeRs_katana_workshop
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true
    code-copy: true

execute:
  freeze: auto
  warning: false
  message: false
